// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1u__39pPF6VCpd4hiNGSDLEOprsOx1g',
    appId: '1:438965558729:android:751bf15c6f48e44dfadc18',
    messagingSenderId: '438965558729',
    projectId: 'fruit-hub-d90c7',
    storageBucket: 'fruit-hub-d90c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbj2mKwvzmPW8UtnmMvyX5ulMp2u15A18',
    appId: '1:438965558729:ios:999159228e4bdea0fadc18',
    messagingSenderId: '438965558729',
    projectId: 'fruit-hub-d90c7',
    storageBucket: 'fruit-hub-d90c7.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbj2mKwvzmPW8UtnmMvyX5ulMp2u15A18',
    appId: '1:438965558729:ios:999159228e4bdea0fadc18',
    messagingSenderId: '438965558729',
    projectId: 'fruit-hub-d90c7',
    storageBucket: 'fruit-hub-d90c7.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );
}
